* Το Δίκτυο
Το δίκτυο υπολογιστών είναι ένα τηλεπικοινωνιακό σύστημα από διασυνδεδεμένους υπολογιστές. 
Οι υπολογιστές θεωρούνται διασυνδεδεμένοι όταν είναι σε θέση να ανταλλάξουν 
πληροφορίες μεταξύ τους.

** Πώς συνδέονται τα PC
Σπίτι μας το τοπικό δίκτυο έχει σαν "κέντρο" του το router, το κουτάκι
που μας δίνει ο ΟΤΕ με κάθε νέα σύνδεση. Αυτό μπορεί να συνδέσει έως και 4
υπολογιστές (μέσω καλωδίων, δεν ασχολούμαστε με WIFI) καθώς έχει 4 θύρες
ethernet.

Στο μαγαζί, όπως γνωρίζεται, έχουμε πάνω από 4 PC. Για να μπορέσουμε να τα
συνδέσουμε όλα μεταξύ τους χρειαζόμαστε ένα άλλο κουτί, που δεν το δίνει ο ΟΤΕ.
Το λεγόμενο switch. Αυτό μπορούμε τα το σκεφτόμαστε σαν πολύμπριζο, αλλά για
ethernet καλώδια.

*** Switches στο μαγαζί
Το μαγαζί έχει 3 switches.
2 πίσω από το ασπρόμαυρο έπιπλο, εκει που βάζουμε το σταθερό,
και 1 πίσω απο τα ηχεία του στερεοφωνικού στην μεγάλη βιβλιοθήκη.

Τα 2 πρώτα, έχουν πάνω τους όλα τα PC από το ταμείο μέχρι την πόρτα
και το άλλο έχει τον server (βλ. παρακάτω) και τα PC του πάνω ορόφου.

** Ο ρόλος του κάθε PC
Δεν είναι όλα τα PC ίδια. Πέρα από τα γνωστά (ο βίνδεο για μοντάζ,
ο 1 για πέρασμα, κτλ κτλ), μερικά PC μας έχουν συγκεκριμένες δουλειές
μέσα στο δίκτυο του μαγαζιού, ας τα πούμε πόστα. 

Σύμφωνα με την κρίση των αντιμιστρατόρων το κάθε PC μπορεί να μοιράζει
συγκεκριμένα πράγματα στο δίκτυο.

*** Fotomada 1
Γνωστός και ως απλά ο 'Ένα' έχει πάνω του αρκετά πράγματα:

- Τη βάση!!
- Τα φακέλια που χρησιμοποιεί κάποιος στην βάρδια (ALBUM_OK, κτλ)

Ο 1 σπάνια κλείνει καθώς κόσμος παίρνει άλμουμ απο το σπίτι του,
θέλει να βλέπει την βάση, κτλ κτλ.

*** Lizzy
Η lizzy, είναι ο σέρβερ μας! 
Είναι ένα κουτί αλλιώτικο απο αυτο στο σπίτι σας
γιατι ο ρόλος του είναι άλλος. Αντί να βλέπει ταινίες και
να παίζει παιχνίδια η Lizzy μπορεί να μοιράζει(serve!) πολλά Terabytes
σε όλο το μαγαζί. Λόγω του πως είναι φτιαγμένη δεν χρειάζεται να κλείνει ποτέ
και αν όλα πάνε καλά, κάποτε θα είναι και η βάση εκεί, και κανένας υπολογιστής
απο τους άλλους δεν θα πρέπει να μένει ανοιχτός. Προς το παρών η lizzy έχει τα εξής:

- Τα master
- Τα video
- Επιτρέπει την πρόσβαση στο μαγαζί απο μακριά (FTP, κτλ)
- Διάφορες μικροδουλειές

*** Τα υπόλοιπα
Φυσικά υπάρχουν και άλλα PC με δουλειές στο δίκτυο,
όπως ο παλιός Βίνδεο που μοιράζει τα παλία βίνδεο (wow).

Τώρα που γνωρίζουμε λίγο πολύ τι παίζει θα εξηγήσω το πλάνο.

** Το Πλάνο
Server σημαίνει σερβιτόρος, δηλαδή σερβίρει. Όλα τα παραπάνω πόστα είναι δουλειές για
server, και όχι για τα άλλα PC, καθώς σερβίρουν κάτι στο δίκτυο.

Το πλάνο είναι σιγά σιγά όλα τα μοιράσματα, οι ρυθμίσεις, η βάση κτλ κτλ,
να μεταφερθούν στην lizzy και σε ότι πάρουμε να της κάνει παρέα (2ο server).

Έτσι θα έχουμε μια κεντρική τοποθεσία για όλα τα DATA αλλά και τα services μας 
(η βάση είναι ένα service) και τα υπόλοιπα PC θα έχουν γρήγορη πρόσβαση σε αυτά.

* Προβλήματα στο δίκτυο
Όλα τα μηχανήματα (εκτός του EPSON) είναι συνδεδεμένα στο δίκτυο.
Για αυτό τυπώνουμε τα εξώφυλλα απο όποιο PC θέλουμε.

Όταν για κάποιον λόγο κάτι στο δίκτυο δεν δουλεύει, σκεφτόμαστε
το πόσο απλά είναι τα πράγματα, δεν φρικάρουμε, και προσπαθούμε
να βρούμε μια λύση, γιατί 9/10 φορές το πρόβλημα λύνεται χωρίς
τη βοήθεια αδμινιστράτορα.

** Αναγνώριση
Το πρόβλημα είναι δικτύου όταν συμβαίνει κάποιο απο αυτά:
- Δεν έχω πρόσβαση στο internet (gmail, κτλ)
- Δεν έχω πρόσβαση στα μοιραζώμενα άλλων PC
- Δεν βλέπω τον εκτυπωτή ενεργό

Αν δεν βλέπω τίποτα μάλλον έχω θέμα εγω (το PC που κάθομαι)
Αν δεν βλέπω 1 μονο πράγμα αλλα όλα τα άλλα είναι κομπλέ, τότε έχει πρόβλημα
το πράγμα που δεν βλέπω.

Η μοναδική φορά που επικοινωνούμε με αδμινιστράτορα δίχως 2η σκέψη
είναι όταν εμείς ΣΙΓΟΥΡΑ ΔΕΝ έχουμε πρόβλημα αλλά η lizzy έχει και 
για x,y λόγους δεν είναι προσβάσιμη.

** Βγαλμένα καλώδια
Πολύ συχνό θέμα, να βγαίνει το καλώδιο.
Είτε απο το PC (πιο συχνό) είτε απο το switch.

Το τσεκάρουμε πάντα πριν οτιδήποτε άλλο.

ΠΟΛΥ ΠΡΟΣΟΧΗ! όταν πειράζουμε τα καλώδια στο switch για να δούμε αν 
έχει βγει κάτι. Απαλά, και χωρίς βιασύνη, πατάμε τα καλώδια προς τα 
μέσα, μπας και κάποιο έχει ξελασκάρει.

** Κλειστά PC
Άμα θέλουμε τα παλιά βίνδεο που είναι στον MONTE-VIDEO και ο 
προαναφερθέντας είναι κλειστός, δεν πρόκειται να τα δούμε. Ποτέ.

Άρα κοιτάμε να είναι ανοιχτά τα PC που θέλουμε να επικοινωνήσουμε.
* Ο linux
Ο linux το μηχάνημα που έχουμε για να βάζουμε στικάκια.

Παλιά είχαμε σοβαρό θέμα καθώς στα PC της Έυης βάζει ο κάθε τυχαίος το
στικάκι του, χωρίς προφύλαξη, και όταν βάζουμε και εμείς το δικό μας
γεμίζει με τις αηδίες που είχαν τα άλλα. 

Ο linux λοιπόν, σαν ανώτερος από τα πάντα, δεν επηρεάζεται από STD's
εεε Ιούς ήθελα να πω.

Άρα εδω και αρκετά χρόνια μέσω αυτού του μηχανήματος περνάμε από 
εξωτερικά μέσα αποθήκευσης (σκληρούς προσωπικούς, στικάκια, κινητά)
σε εσωτερικά (PARAGGELIES_TEMP).

** NTFS και το πρώτο στικάκι
Τα στικάκια που στέλνουμε στην Ευη είναι φορμαρισμένα ως NTFS.

Δεν χρειάζεται να ξέρετε τι είναι τούτο, απλά να ξέρετε οτι 99,9%
ο πελάτης ΔΕΝ θα έχει NTFS στικάκι.

Ο linux είναι προγραμματισμένος το πρώτο στικάκι που του μπαίνει
να το διαβάζει σαν NTFS, και να το μοιράζει στο δίκτυο στην τοποθεσία \\linux\usbstick, 
καθώς αυτή είναι η κύρια χρήση του.

Όταν θέλουμε να βάλουμε κάποιο εξωτερικό μέσω αποθήκευσης, πρέπει να μπαίνει 2ο
για 2 λόγους:

- Ίσως να μην είναι NTFS 
  + άρα θα προσπαθεί να διαβάσει κάτι που δεν γνωρίζει
  + σαν να πας να διαβάσεις ισπανικό κείμενο, γνωρίζοντας μόνο αγγλικά. (μπορείς να διαβάσεις, αλλα δεν καταλαβαίνεις τι λέει)
- Δεν θέλουμε να το μοιράσουμε σε όλο το μαγαζί

Όταν μπεί 2ο αντί να διαβάζεται σαν NTFS αναγνωρίζει αυτόματα το PC τι είδους είναι και τα κάνει όλα σωστά.

** Μεταφορά μεγάλων αρχείων απο/προς εξωτερικό σκληρό προς/απο μαγαζί
Αν έχουμε κάποιο μεγάλο αρχείο (Γάμος, βίδεο) που θέλουμε να μεταφέρουμε
βάζουμε τον δίσκο μας (2ο πάντα), και μέσα απο τον linux μπαίνουμε στο δίκτυο του μαγαζιού
(με κωδικό orko) φυσικά και κάνουμε copy/paste κατευθείαν στο/απ'το μηχάνημα που θέλουμε.

** Αντιμετώπιση προβλημάτων
Υπάρχουν πολλοί τρόποι να λυθεί το κάθε πρόβλημα που προκύπτει, όμως ένας
φωνάζει ως ο πιο απλός: Restart

Αν για κάποιον λόγο το PC δεν κάνει αυτό που θέλουμε το ξεκινάμε απο την αρχή.

Βγάζουμε ΟΛΑ τα στικάκια, κάνουμε restart, βάζουμε πρώτα το στικ της ομάδας
και μετά αφού μπει καλά, βάζουμε ότι άλλο θέλουμε.

Αν πάλι το στικάκι για την Έυη έχει θέμα, το βγάζουμε, βάζουμε άλλο και ενημερώνουμε
κάποιον αδμιν για να το φορμάρει ξανά.
