* Το Δίκτυο
Το δίκτυο υπολογιστών είναι ένα τηλεπικοινωνιακό σύστημα από διασυνδεδεμένους υπολογιστές. 
Οι υπολογιστές θεωρούνται διασυνδεδεμένοι όταν είναι σε θέση να ανταλλάξουν 
πληροφορίες μεταξύ τους.

** Πώς συνδέονται τα PC
Σπίτι μας το τοπικό δίκτυο έχει σαν "κέντρο" του το router, το κουτάκι
που μας δίνει ο ΟΤΕ με κάθε νέα σύνδεση. Αυτό μπορεί να συνδέσει έως και 4
υπολογιστές (μέσω καλωδίων ether net, δεν ασχολούμαστε με WIFI) καθώς έχει 4 θύρες.

Στο μαγαζί, όπως γνωρίζεται, έχουμε πάνω από 4 PC. Για να μπορέσουμε να τα
συνδέσουμε όλα μεταξύ τους χρειαζόμαστε ένα άλλο κουτί, που δεν το δίνει ο ΟΤΕ.
Το λεγόμενο switch. Αυτό μπορούμε τα το σκεφτόμαστε σαν πολύμπριζο, αλλά για
ethernet καλώδια.

*** Switches στο μαγαζί
Το μαγαζί έχει 3 switches.
2 πίσω από το ασπρόμαυρο έπιπλο, εκει που βάζουμε το τηλέφωνο
και 1 πίσω απο τα ηχεία του στερεοφωνικού στην μεγάλη βιβλιοθήκη.

Τα 2 πρώτα, έχουν πάνω τους όλα τα PC από το ταμείο μέχρι την πόρτα
και το άλλο έχει τον server (βλ. παρακάτω) και τα PC του πάνω ορόφου.

** Ο ρόλος του κάθε PC
Δεν είναι όλα τα PC ίδια. Πέρα από τα γνωστά (ο βίνδεο για μοντάζ,
ο 1 για πέρασμα, κτλ κτλ), το κάθε PC έχει συγκεκριμένες δουλειές
μέσα στο δίκτυο του μαγαζιού, ας τις πούμε πόστα.

*** Fotomada 1
Γνωστός και ως απλά ο 'Ένα' έχει πάνω του αρκετά πράγματα:

- Τη βάση
- Το πέρασμα
- Τα φακέλια που χρησιμοποιεί κάποιος στην βάρδια (ALBUM_OK, κτλ)

Ο 1 σπάνια κλείνει καθώς κόσμος παίρνει άλμουμ απο το σπίτι του,
θέλει να βλέπει την βάση, κτλ κτλ.

*** Lizzy
Η lizzy, είναι ο σέρβερ μας! 
Είναι ένα κουτί αλλιώτικο απο αυτο στο σπίτι σας
γιατι ο ρόλος του είναι άλλος. Αντί να βλέπει ταινίες και
να παίζει παιχνίδια η Lizzy μπορεί να μοιράζει(serve!) πολλά Terabytes
σε όλο το μαγαζί. Λόγω του πως είναι φτιαγμένη δεν χρειάζεται να κλείνει ποτέ.

Προς το παρών η lizzy έχει τα εξής:

- Τα master
- Τα video
- Επιτρέπει την πρόσβαση στο μαγαζί απο μακριά (FTP, κτλ)
- Διάφορες μικροδουλειές

*** Τα υπόλοιπα
Φυσικά υπάρχουν και άλλα PC με δουλειές στο δίκτυο,
όπως:
 - ο παλιός Βίνδεο που μοιράζει τα παλία βίνδεο (wow)
 - ο linux που θα τα πω παρακάτω τα κουμάντα του
 - τα απλά preview
 - o facebook
 - Ο 5 και ο 6 (κάνουν βάρδια όταν τα άλλα είναι γεμάτα)
 - ο γουτεμβέργιος (Που έχει τον EPSON και το lightroom)

** Το Πλάνο
Τώρα που γνωρίζουμε λίγο πολύ τι παίζει θα εξηγήσω το πλάνο.

Server σημαίνει σερβιτόρος, δηλαδή σερβίρει. Όλα τα παραπάνω πόστα είναι δουλειές για
server, και όχι για τα άλλα PC, καθώς σερβίρουν κάτι στο δίκτυο.

Το πλάνο είναι σιγά σιγά όλα τα μοιράσματα, οι ρυθμίσεις, η βάση κτλ κτλ,
να μεταφερθούν στην lizzy και σε ότι πάρουμε να της κάνει παρέα (2ο server).

Έτσι θα έχουμε μια κεντρική τοποθεσία για όλα τα DATA αλλά και τα services μας 
(η βάση είναι ένα service) και τα υπόλοιπα PC θα έχουν γρήγορη πρόσβαση σε αυτά.

* Προβλήματα στο δίκτυο
Όλα τα μηχανήματα (εκτός του EPSON) είναι συνδεδεμένα στο δίκτυο.
Για αυτό τυπώνουμε τα εξώφυλλα απο όποιο PC θέλουμε.

Όταν για κάποιον λόγο κάτι στο δίκτυο δεν δουλεύει, σκεφτόμαστε
το πόσο απλά είναι τα πράγματα, δεν φρικάρουμε, και προσπαθούμε
να βρούμε μια λύση, γιατί 9/10 φορές το πρόβλημα λύνεται χωρίς
τη βοήθεια αδμινιστράτορα.

** Αναγνώριση
Το πρόβλημα είναι δικτύου όταν συμβαίνει κάποιο απο αυτά:
- Δεν έχω πρόσβαση στο internet (gmail, κτλ)
- Δεν έχω πρόσβαση στα μοιραζώμενα άλλων PC
- Δεν βλέπω τον εκτυπωτή ενεργό

Αν δεν βλέπω τίποτα μάλλον έχω θέμα εγω (το PC που κάθομαι)
Αν δεν βλέπω 1 μονο πράγμα αλλα όλα τα άλλα είναι κομπλέ, τότε έχει πρόβλημα
το πράγμα που δεν βλέπω.

Η μοναδική φορά που επικοινωνούμε με αδμινιστράτορα δίχως 2η σκέψη
είναι όταν εμείς ΣΙΓΟΥΡΑ ΔΕΝ έχουμε πρόβλημα αλλά η lizzy έχει και 
για x,y λόγους δεν είναι προσβάσιμη.

** Βγαλμένα καλώδια
Πολύ συχνό θέμα, να βγαίνει το καλώδιο.
Είτε απο το PC (πιο συχνό) είτε απο το switch.

Το τσεκάρουμε πάντα πριν οτιδήποτε άλλο.

ΠΟΛΥ ΠΡΟΣΟΧΗ! όταν πειράζουμε τα καλώδια στο switch για να δούμε αν 
έχει βγει κάτι. Απαλά, και χωρίς βιασύνη, πατάμε τα καλώδια προς τα 
μέσα, μπας και κάποιο έχει ξελασκάρει.

** Κλειστά PC
Άμα θέλουμε τα παλιά βίνδεο που είναι στον MONTE-VIDEO και ο 
προαναφερθέντας είναι κλειστός, δεν πρόκειται να τα δούμε. Ποτέ.

Άρα κοιτάμε να είναι ανοιχτά τα PC που θέλουμε να επικοινωνήσουμε.
* Ο linux
Ο linux το μηχάνημα που έχουμε για να βάζουμε στικάκια.

Παλιά είχαμε σοβαρό θέμα καθώς στα PC της Έυης βάζει ο κάθε τυχαίος το
στικάκι του, χωρίς προφύλαξη, και όταν βάζουμε και εμείς το δικό μας
γεμίζει με τις αηδίες που είχαν τα άλλα. 

Ο linux λοιπόν, σαν ανώτερος από τα πάντα, δεν επηρεάζεται από STD's
εεε Ιούς ήθελα να πω.

Άρα εδω και αρκετά χρόνια μέσω αυτού του μηχανήματος περνάμε από 
εξωτερικά μέσα αποθήκευσης (σκληρούς προσωπικούς, στικάκια, κινητά)
σε εσωτερικά (PARAGGELIES_TEMP).

** NTFS και το πρώτο στικάκι
Τα στικάκια που στέλνουμε στην Ευη είναι φορμαρισμένα ως NTFS.

Δεν χρειάζεται να ξέρετε τι είναι τούτο, απλά να ξέρετε οτι 99,9%
ο πελάτης ΔΕΝ θα έχει NTFS στικάκι.

Ο linux είναι προγραμματισμένος το πρώτο στικάκι που του μπαίνει
να το διαβάζει σαν NTFS, και να το μοιράζει στο δίκτυο στην τοποθεσία \\linux\usbstick, 
καθώς αυτή είναι η κύρια χρήση του.

Όταν θέλουμε να βάλουμε κάποιο εξωτερικό μέσω αποθήκευσης, πρέπει να μπαίνει 2ο
για 2 λόγους:

- Ίσως να μην είναι NTFS 
  + άρα θα προσπαθεί να διαβάσει κάτι που δεν γνωρίζει
  + σαν να πας να διαβάσεις ισπανικό κείμενο, γνωρίζοντας μόνο αγγλικά. (μπορείς να διαβάσεις, αλλα δεν καταλαβαίνεις τι λέει)
- Δεν θέλουμε να το μοιράσουμε σε όλο το μαγαζί

Όταν μπει 2ο αντί να διαβάζεται σαν NTFS αναγνωρίζει αυτόματα το PC τι είδους είναι και τα κάνει όλα σωστά.

** Μεταφορά μεγάλων αρχείων απο/προς εξωτερικό σκληρό προς/απο μαγαζί
Αν έχουμε κάποιο μεγάλο αρχείο (Γάμος, βίδεο) που θέλουμε να μεταφέρουμε
βάζουμε τον δίσκο μας (2ο πάντα), και μέσα απο τον linux μπαίνουμε στο δίκτυο του μαγαζιού
(με κωδικό orko φυσικά) και κάνουμε copy/paste κατευθείαν στο/απ'το μηχάνημα που θέλουμε.

** Αντιμετώπιση προβλημάτων
Υπάρχουν πολλοί τρόποι να λυθεί το κάθε πρόβλημα που προκύπτει, όμως ένας
είναι ο πιο απλός: Restart.

Αν για κάποιον λόγο το PC δεν κάνει αυτό που θέλουμε το ξεκινάμε απο την αρχή.

Βγάζουμε ΟΛΑ τα στικάκια, κάνουμε restart, βάζουμε πρώτα το στικ της ομάδας
και μετά αφού μπει καλά, βάζουμε ότι άλλο θέλουμε.

Αν πάλι το στικάκι για την Έυη έχει θέμα στο μοίραζμα, το βγάζουμε, βάζουμε άλλο και ενημερώνουμε
κάποιον αδμιν για να το φορμάρει ξανά.

* Εκτυπωτής cannon
Ο εκτυπωτής cannon είναι για τετραφακούς και εξώφυλλα.

Για να λειτουργήσει πρέπει να είναι ανοιχτος ο ένα για να τον μοιράζει στο δίκτυο.
Απο εκεί και πέρα όσα PC κάνουν βάρδια μπορούν να τυπώσουν.

** Profiles
Υπάρχουν διάφορα προφιλ για το κάθε είδος τυπώματος.
  - DvdCover B&W για εξώφυλλα
  - 10χ15 για τις glossy (γενικής, δίπλωμα διαβατήριο)
  - Id για ταυτότητα

** Αντιμετώπιση προβλημάτων
Κοιτάμε να είναι ανοιχτός ο εκτυπωτής, και το USB να είναι στον 1 βαλμένο καλά.

Μπορούμε να δούμε αν ο 1 τον "διαβάζει" πηγαίνοντας στον πίνακα ελέγχου και πατώντας
στους εκτυπωτές! ==//FIXME==
* Ftp
Ftp σημαίνει file transfer protocol. Ή στα Ελληνικά πρωτόκολλο μεταφοράς αρχείων.

Το μαγαζί έχει στημένο ftp server στον 1, που σημαίνει πως μπορούμε να 
συνδεόμαστε από μακριά σε αυτόν. Μέσω ftp μπορούμε να μεταφέρουμε αρχεία απο το
μαγαζί σπίτι μας και το αντίστροφο.

Για να το πετύχουμε αυτό χρησιμοποιούμε ένα ftp client όπως το [[https://filezilla-project.org/][filezilla]].

** Setup
==//SETUP FILEZILLA==
* Ψηφιακοί χώροι αποθήκευσης
Το μαγαζί έχει διάφορους χώρους για αποθήκευση ψηφιακού υλικού.
Πρέπει ο κάθε ένας να γνωρίζει που είναι τα πάντα που μπορεί να χρειαστούν
στην βάρδια. Δεν έχει νόημα να τα γράψω εδώ καθώς είναι δυναμικά αυτά.

Οι σκληροί του μαγαζιού είναι SSD ή HDD.
Η ώρα χρήσης ενός δίσκου έχει να κάνει με το πόσο συχνά γράφουμε ή
διαβάζουμε από αυτόν.

** HDD
Οι κλασικοί μαγνητικοί δίσκοι που όλοι ξέρουμε και αγαπάμε.
Στιβαροί όσο δεν τους κοπανάμε αλλά σχετικά αργοί για τα σημερινά δεδομένα.
Έχουν πολύ μεγάλο προσδοκώμενο όριο ζωής (ώρες χρήσης).

Κατάλληλοι για αποθήκευση αρχείων και media.

** SSD
Καινούργιας τεχνολογίας δίσκοι με πολύ μεγαλύτερή χρονική απόδοση 
σε σχέση με τους HDD αλλά και πολύ χαμηλότερο προσδοκώμενο όριο ζωής (ώρα χρήσης). Πρακτικά
μας δίνουν πολύ ταχύτητα αλλά χαλάνε γρήγορα.

Κατάλληλοι για την εγκατάσταση λογισμικού ή/και λειτουργικού συστήματος 
(photoshop/windows).

** Διαφορές
Στα καλά PC το λογισμικό καθώς και τα προγράμματα είναι εγκατεστημένα στον ==C://== 
ο οποίος είναι SSD.

Όλα τα υπόλοιπα data (φωτό, video, κλπ) είναι σε HDD.

Επίσης στον video έχει άλλον 1 SSD για να κάνει τα cache των μοντάζ καθώς χρειάζεται
γρήγορος δίσκος για αυτό.

** Τρόπος χρήσης
Ο απλός φωτομαδίτης, είτε κάνει δική του δουλειά είτε κάνει βάρδια, ΔΕΝ ΠΡΕΠΕΙ ΠΟΤΕ
να σώζει σε SSD ούτε για λίγο.

Να σημειωθεί οτι η Επιφάνεια Εργασίας στα windows 7 είναι αναγκαστικά στον SSD και μέχρι
να το γυρίσουμε στα windows 10 δεν σώζουμε αρχεία στην επιφάνεια εργασίας.

Στους SSD γράφουν μόνο ο Περασματίας όταν κάνει πέρασμα και ο βιντεάς όταν κάνει cache 
το μοντάζ του. ==//Γραφει και κάνας άλλος;==

Στους υπόλοιπους δίσκους επίσης δεν σώζουμε αρχεία όπου νάνε. Υπάρχουν τοποθεσίες για την
κάθε δουλειά, και αν δεν έχει κάτι που θέλουμε το μιλάμε με έναν admin και δεν το βάζουμε 
όπου μας καπνίσει. 

Τις προσωπικές δουλειές τις κρατάμε σε δικούς μας σκληρούς και όχι σε σκληρούς του μαγαζιού.

Τα προσωρινά αρχεία (pdf, mp3, κτλ) που κατεβάζουμε για εμάς, δεν τα παρατάμε στα Downloads
ή όπου αλλού κατέβηκαν, αλλά είτε τα σβήνουμε είτε τα βάζουμε κάπου ωραία και καλά, με σκοπό
να τα σβήσουμε σε λίγο καιρό. Μέχρι τότε ας τα πάρουμε σπίτι αν τα θέλουμε τόσο πολύ.

* Χρήση υπολογιστών
** Βάρδια
** Βίνδεο
** Ξεσκάρτ
